app: front

image:
  name: nelson9291/front
  tag: 2.3.0

namespace: default

labels:
  owner: alex

replicas:
  min: 1
  max: 1

averageUtilization:
  cpu: 50
  memory: 80

variables:
  KEYCLOAK_REALM: "template"
  KEYCLOAK_CLIENT: "template-service"
  KEYCLOAK_URL: https://javaforall.tech/oauth/auth/
  SPRING_PROFILES_ACTIVE: prod

secrets:
  KEYCLOAK_SECRET: f6204f95-4150-48d0-b13b-718d44a6b3b7