server:
  port: 8080
  servlet:
    context-path: /api/front/

spring:
  application:
    name: front-service
  profiles:
    default: dev

logging:
  config: classpath:logback-spring.xml
  service:
    enable: true

management:
  endpoints:
    web:
      exposure:
        include: [health, info, threaddump, heapdump, prometheus]
#      base-path: /http
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]" : true
    use-global-registry: false
    tags:
      application: ${spring.application.name}
#  server:
#    port: 9090
  endpoint:
    health:
      show-details: ALWAYS
springdoc:
  packages-to-scan: my.company.front
  swagger-ui:
    path: /swagger-ui.html
